[workspace]

[package]
name = "linksider"
version = "0.1.0"
edition = "2021"

[package.metadata.geng]
assets = ["assets", "levels"]

[dependencies]
geng.git = "https://github.com/geng-engine/geng"
logicsider.path = "logicsider"
autotile.path = "autotile"
serde = "1"
