[workspace]

[package]
name = "linksider"
version = "0.1.0"
edition = "2021"

[dependencies]
geng.git = "https://github.com/geng-engine/geng"
logicsider.path = "logicsider"
ldtk.path = "ldtk"
serde = "1"
