fov = 12
camera_speed = 2
animation_time = 0.2
cell_pixel_size = 16
border_radius_pixels = 4

[sound]
volume = 0.1

[controls]
left = ["Left", "A"]
right = ["Right", "D"]
skip = ["Space"]
restart = ["R"]
undo = ["Z", "U"]
redo = ["X", "Y"]
next_player = ["Tab", "Up"]
prev_player = ["Down"]
escape = ["Escape"]

[controls.cheats]
next_level = "P"
prev_level = "O"
effect = { jump = "J", delete = "Delete" }

[camera_controls]
min_fov = 5
max_fov = 50
zoom_speed = 0.1
drag = "Middle"

[editor.level]
default_fov = 15
index_size = 0.3
index_color = "white"
brush_preview_opacity = 0.5
grid_color = "#7775"

[editor.level.brush_wheel]
radius = 3
inner_radius = 2
color = "#777"

[editor.level.controls]
toggle = "F1"
create = "Left"
delete = "Right"
choose = "Tab"
pick = "Q"
grid = "G"
rotate = "R"

[editor.world]
fov = 15
level_icon_size = 0.9
margin = 5
preview_texture_size = 128

[editor.world.controls]
insert = "I"
delete = "X"
copy = "C"
paste = "P"
