camera_speed = 2
animation_time = 0.2
cell_pixel_size = 16
border_radius_pixels = 4

[experimental]
magnet_logic = "Always90" # "Input", "Always90", "Always180"

[sound]
volume = 0.1

[controls]
left = ["Left", "A"]
right = ["Right", "D"]
skip = ["Space"]
restart = ["R"]
undo = ["Z", "U"]
redo = ["X", "Y"]
next_player = ["Tab", "Up"]
prev_player = ["Down"]

[controls.cheats]
next_level = "PageUp"
prev_level = "PageDown"
effect = { jump = "J", delete = "Delete" }
