camera_speed = 10
animation_time = 0.2
cell_pixel_size = 16
border_radius_pixels = 4

[sound]
volume = 0.1

[controls]
left = ["Left", "A"]
right = ["Right", "D"]
skip = ["Space"]
next_player = ["Tab", "Up"]
prev_player = ["Down"]

[controls.cheats]
next_level = "PageUp"
prev_level = "PageDown"
effect = { jump = "J", delete = "Delete" }
