camera_speed = 2
animation_time = 0.2
cell_pixel_size = 16
border_radius_pixels = 4
deselected_player_color = "#fff7"
zzz_time = 30
happy = false

[popup]
ui_fov = 6

[play]
ui_fov = 6
fov = 12

[input]
min_drag_distance = 5
max_click_time = 0.5
zoom_speed = 1

[level_select]
fov = 12
ui_fov = 6
level_icon_offset = [0, 0.0625]
level_icon_size = 0.625
icon_color = "#46425e"
connector_width = 0.25
connector_color = "#ffb0a3"
camera_speed = 5
other_group_opacity = 0.5
select_scale = 1.5

[level_select.controls]
left = ["Left", "A", "H"]
right = ["Right", "D", "L"]
up = ["Up", "W", "K"]
down = ["Down", "S", "J"]
play = ["Space", "Enter", "O"]

[render.shadow]
offset = [0.125, -0.125]
opacity = 0.2

[sound]
volume = 0.1

[controls]
left = ["Left", "A"]
right = ["Right", "D"]
skip = ["Space"]
restart = ["R"]
undo = ["Z", "U"]
redo = ["X", "Y"]
next_player = ["Tab", "Up"]
prev_player = ["Down"]
escape = ["Escape"]

[controls.cheats]
next_level = "P"
prev_level = "O"
effect = { jump = "J", delete = "Delete" }

[editor.level]
default_fov = 15
min_fov = 5
max_fov = 30
ui_fov = 6
margin = 15
index_size = 0.3
index_color = "white"
preview_opacity = 0.5
grid_color = "#7775"
warning_size = 24
warning_color = "#ff0"
# autosave_timer = 10

[editor.level.tool_wheel]
item_scale = 0.3
radius = 1
inner_radius = 0.7
color = "#777"

[editor.level.controls]
toggle = "F1"
choose = "Tab"
pick = "Q"
grid = "G"
rotate = "R"
reset_to_last_save = "F7"

[editor.world]
default_fov = 15
min_fov = 5
max_fov = 30
ui_fov = 6
level_icon_size = 0.9
margin = 5
preview_texture_size = 128

[editor.world.controls]
insert = "I"
delete = "X"
copy = "C"
paste = "P"
rename = "R"
