allow_unstable_player_selection = false

[magnet]
continue = "Always" # "Input", "Always", "Never"
continue_horizontal = false
continue_when_magneted = false
weak_on_other_side = false

[entities.Player]
block = true
trigger = true
player = true

[entities.Crate]
block = true
trigger = true
pushable = false

[entities.Box]
block = true
trigger = true
pushable = true

[entities.DisableBox]
block = true
pushable = true

[entities.block]
block = true
trigger = true
static = true

[entities.disable]
block = true
static = true

[entities.cloud]
trigger = true
static = true
