allow_unstable_player_selection = false
magnet_continue = "Always" # "Input", "Always", "Never"

[entities.Player]
block = true
trigger = true
player = true

[entities.Crate]
block = true
trigger = true
pushable = false

[entities.Box]
block = true
trigger = true
pushable = true

[entities.DisableBox]
block = true
pushable = true

[entities.block]
block = true
trigger = true
static = true

[entities.disable]
block = true
static = true

[entities.cloud]
trigger = true
static = true
