theme = "no-style-please"

base_url = "https://kuviman.github.io/linksider"

title = "LinkSider"
description = "Puzzle Game"

compile_sass = true

build_search_index = true

[markdown]
highlight_code = true

[extra]
