[[textures]]
anchor = "TopLeft"
texture = "topleftUIBG.png"

[[textures]]
anchor = "TopRight"
texture = "toprightUIBG.png"

[[textures]]
anchor = "BottomRight"
texture = "bottomrightUIBG.png"

[[textures]]
anchor = "BottomLeft"
texture = "bottomleftUIBG.png"
