name: CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-web:
    name: Build
    runs-on: ubuntu-latest
    container: kuviman/geng
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: cargo geng build --release --target wasm32-unknown-unknown
      - name: Upload artifacts (web)
        uses: actions/upload-artifact@v2
        with:
          name: web
          path: target/geng

  build-native:
    name: Build (Native)
    runs-on: ${{ matrix.platform.runs-on }}
    strategy:
      matrix:
        platform:
          - runs-on: ubuntu-latest
            channel: linux
          - runs-on: macos-latest
            channel: mac
          - runs-on: windows-latest
            channel: windows
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install things
        if: matrix.platform.channel == 'linux'
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev libudev-dev
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - name: Install cargo-geng
        run: cargo install cargo-geng --git https://github.com/kuviman/geng
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: geng
          args: build --release
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.platform.channel }}
          path: target/geng

  deploy-website:
    name: Deploy Website
    permissions:
      contents: write
    if: github.ref == 'refs/heads/main' && github.repository_owner == 'kuviman'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build
        uses: shalzz/zola-deploy-action@v0.17.1
        env:
          BUILD_DIR: website
          BUILD_THEMES: false
          BUILD_ONLY: true
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: website/public
          clean-exclude: |
            play

  deploy-web:
    name: Deploy (Dev)
    permissions:
      contents: write
    if: github.ref == 'refs/heads/dev' && github.repository_owner == 'kuviman'
    runs-on: ubuntu-latest
    needs:
      - build-web
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: web
          target-folder: play/web

  deploy-native:
    name: Deploy (Dev)
    permissions:
      contents: write
    if: github.ref == 'refs/heads/dev' && github.repository_owner == 'kuviman'
    runs-on: ubuntu-latest
    needs:
      - build-native
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Create archives
        run: |
          mkdir native
          for platform in linux windows mac; do
            name=${{ github.event.repository.name }}-$platform
            mv $platform $name
            zip -r native/$name.zip $name
          done
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: native
          target-folder: play/native
